travis:
  secure:
    BINSTAR_TOKEN: viqGMq7GhqFJQZFI5xJnm46k8AY5RdxLwPANN8yYMcuTdbp5mfBoiN2ehmPiGGpXT9htSaS3e10PgJDO4mk6fgfl3ZJLDqjt8mU2h+5w+MrxlaplBYKukoNPHSVTjx2kNoBmWdmLIC7bTE7EGKwA3BqKvCk0aHZ/9LNoOKArX7x1+FJDNOxMAjdvoZxZt7scBipsrEl15w9PXzX4T8GD4IvcMf0ugg4EE28kAwJQ6bAYptegB5+IHF3g5dDiSfTb2ec7LSFyJgAnXIsn3wp3wpu2c+5zC5TnIIZLlTuWCQ+7MsOEU4XqItk1Vip5m3mdaPm2nGcioFt9NLjTp6c/wp1+IUgSLzzrpL6OMJEtjFl5WHS5SKJikTH/stD8jRVZV3+mX+0YsEDKWPAAhysxjY58U/XBBvsjuZXYxNhYiW85i7x/oazgDdU+Bukivs5SHtYYl3wfFATQVgdMpGPjCKWNbEi6UQCHTYrvBLL/MMt2qyhrrR9stJ5w+nttfrqTnWOKiL+Jy+T9SFS+bPv6YO7ZgvNx4z/3BfwOaQNldc5NqgEaPEov3dZ63kIvKK7XHSSSFF22jUmwZJnczYo6gPtzrhZoZgsivDDIxhHMy2DTTaYuAvp2zweD0KfxBIj41pAPTq4Cr8Kbcrsm+HCkseUAcCe3OgqK4176tvF+eU4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
