travis:
  secure:
    BINSTAR_TOKEN: L33Gt5dwXkItmk5mB4DCqegADlQPQnm8VdzmZQLPzBnUE1Ioatm+ITgZasKkGMTxclgkSb6YY+WGWYZIz/Z83dYUDHsE+ZT7eTUy6HSCem9NFNoNkjESgeyGGHV5mOJlpHYo982jt+26QiLF7FmV8ybq/IjjHnVA78HJ92w2PHvmCNIFxtHnkl2tMWi16R7e21QYQMtvrNrZPqg7hLPtBiktu4rNSeQ41fPgwvIDG1uAz3u13WF4S2ZGOF721WmEXiW/jC7K0/7YwbVKTc9xkOWCsoUJ1jnNA/Hvf3nfshxVxZ8u8MAkUAzjY5NiCXF6v8n1X9Arwp7jwrPqxOOv/uwXaP2lM3cu0tLktefTMxEnUPrZN497KdC3nyKLQItzNgHYmUVxH6aw1rpAd/cJ2fokl/blsBEYrJQxzC7Ro/ZpXb8ukeLMpq9g3CN8E6mq4TfStPQBuvFaIpHmxFPeCBkQRRptMpdDZEQoFiGlqob5u8DGIuMtXmOKRwTKR2HBsu7IRr2Aduzfse2RDN2Kjtr2ieV2z9FKCnMXwBQPEFKXSITIg0jOMfKmBiMCmmA9MmkA0jxrtcXX1haEYpKdujN9Yw9ygmWQm58m0Ih6zzQIo1M/Rjmi20oERTBkaqxnyJ0/gO+jTGX+tRTXxGNfZXbur1HGUKZQHFI7AOx7XKA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
