travis:
  secure:
    BINSTAR_TOKEN: c77dZ7ioLzQrFe0SnS5ko09KsLg40rUIPEYmJ8Sh3bOKaURUE708/X0u4dO75J4PCJ6ULpbfPblIa2yglOpKfB0Ppi759C7yBHOaaJPD95LtTUYVLa7TQeiKJn8WLpRgW91/3wvy1TjiPJcrzHu8c5cfLKAGKjnYCNBlx3Eu8XN/+63igPWMTww+6vVqxNRbdr25O7Z8DyeSBygyjDta75XWQCz6ldfkJr+6OMDEQTVCSbrY5e45wC0C+NFHpD7/dVufW/rVe19trvjj/Re65X2wfQgbRKRANEabaSBXE868ckdIWg0iswNrA44mSrmYqw7MQKleZR8pglLfXNrWktyDaeOHsM8oP8TYMb30rfasy2jec7LMKRbhKQSRTiIg6+pkAe2y4KNrYv/YWlpD6U/X/iclTyIFdScBVt0R7O6VjqoYl53Z4gXmiAcT32FN0ht36j/ClAu+zMVEW9jFlsViYoHHyl1kfhiIEKySlyuvyEPR04Nz/wZCjFftie0975Ko2vD+g8KPxa9INug0VAbxFL51jfhc/CKHbUO9q6vX3LtzfWN5lmaIo3QfOWN7bvhx+RRAG7GS+DtdCScPs8RLOcJcsVO72RNmrRXvywFIUyPqC3T3vYDZByj7cG8k/ewRsiEOwaMGgnBo7V4olQI9e2V2r1p9gqkAkbXYcFw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
