appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: HVO8hUp1uzlivUxGfcr21LjXqaiJPz00+PVqKcNvJMNckreBWyqofsZcsodHaWH+8SMZBRfEcYb4Yg+Xq+/RBc3roHZpH5jg4zH6qiWyfT7ihnO1VfsTrtQLK4rfDUPGEXGjGbCi/a8ZcI/ipRnO1oVoe4u4Hz7mNXR1KYtOy3ushXYQMTzbjAtIYg7lZbXn40zo+rRiT5LPkwr9Yt18wq5fTfDP3d6JUgGAFVZGat2hg6nqbMmAdfKbLQ2y2Wex+YnUfprcgOpz8ZKpBpSpIF3taWujCBskTSi+992zmHftH+pXaJJvDNJHulTEW8qxtQP4Ncb8uCZnx07qegaF/O2qE0CbrJr8OrDWP5xkg48Re2lTn9D3UUNcfTzddRlCmbbwD3AZaffH99+o0DPVF1qluo+6SJHJh8D0yp/caL4BwQqwnsW30IUeONzmcKDNc9yEeSmud4Yj4QRxF4Wo0nf0BaeT6Jd5ljppBKYDK31YpBbumPGtwnvPpsbMODckrph6twgSH7HtoxrdWY6ZxixHF1E8KZM0xiEvC4Fbns8xhF4ArZAFQCHVSskVWwIwNZWgMBa5l/QJgqn0YkedKlyhMOCMOlHNd1szNtfXU5I7/yUOe30cFiUj3Df8Bl0F/F9iIX/e+gMEpheIpV+08HlP1h49Y0Y1YXlvsoXmS+M=}
